version: '3'

services:
  lotus:
    image : ${REPO_HOST}/lotus:${REPO_TAG}
    container_name: ${PREFIX}_lotus
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "1234"
    command: ./lotus daemon
    volumes:
      - lotus:/root/.lotus
  lotus_storage_miner:
    image : ${REPO_HOST}/lotus:${REPO_TAG}
    container_name: ${PREFIX}_lotus_storage_miner
    depends_on:
      - lotus
    command: ./lotus-storage-miner run      
    volumes:
      - lotus:/root/.lotus
      - lotusstorage:/root/.lotusstorage
      - paramcache:/var/tmp/filecoin-proof-parameters    
volumes:
  lotus:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data/lotus
      o: bind
  lotusstorage:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data/lotus
      o: bind
  paramcache:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data/paramcache
      o: bind
  