FROM golang:1.13.4

ENV VERSION 1.0

WORKDIR /workdir

RUN apt update -y && apt install -y llvm clang libclang-dev mesa-opencl-icd ocl-icd-opencl-dev

COPY ./build/bootstrap/lotus.genesis /root/.lotus

COPY ./lotus /workdir/

CMD ["/workdir/lotus","daemon", "--bootstrap=false"]